# Generated by Django 5.2.6 on 2025-12-10 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchapp', '0003_cartitem_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='related_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mywatchapp.relatedimagedetail'),
        ),
    ]
