# Generated by Django 5.2.6 on 2025-12-11 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchapp', '0004_cartitem_related_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='related_image',
        ),
    ]
