# Generated by Django 5.2.6 on 2025-12-11 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchapp', '0005_remove_cartitem_related_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='related_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mywatchapp.productrelatedimages'),
        ),
    ]
