# Generated by Django 5.2.6 on 2025-12-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchapp', '0008_orderitem_related_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutMission', models.TextField()),
                ('aboutVision', models.TextField()),
            ],
        ),
    ]
